# This file is generated by ConfigPorperties.generator.py, do not modify this file directly.
import json
from typing import List, Dict


class JSONLOAD:
    def __init__(self, config_file: str):
        """Initialize JSONLOAD by loading a JSON configuration file."""
        with open(config_file, 'r') as f:
            json_object = json.load(f)
        self.fonts: List[Dict[str, str]] = json_object.get('fonts', None)  # 
        self.font_list: List[int] = json_object.get('font_list', None)  # 
        self.time_font: int = json_object.get('time_font', None)  # 
        self.spacing: int = json_object.get('spacing', None)  # 
        self.shade_offset: List[int] = json_object.get('shade_offset', None)  # 
        self.text_color: List[int] = json_object.get('text_color', None)  # 
        self.shade_color: List[int] = json_object.get('shade_color', None)  # 
        self.text_list: List[List[Dict[str, str]] | List[str]] = json_object.get('text_list', None)  # 
        self.pos_list: List[List[int]] = json_object.get('pos_list', None)  # 

    def __repr__(self) -> str:
        return str(self.__dict__)